config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'games#index'
  resources :users
  get '/auth/:provider/callback' => 'sessions#create'
  get '/auth/failure' => 'sessions#failure'
  get '/signout' => 'sessions#destroy', as: :signout
  get '/signin' => 'sessions#new', as: :signin
  # post '/open' => 'home#open', as: :open
  # patch '/join/:id/:team_id' => 'home#join', as: :join
  # get '/game/:id' => 'home#game', as: :game
  resources :games do
    resources :teams do
      patch 'join', on: :member
    end
    resources :players do
      member do
        get 'find_opponent'
        get 'use_cards'
        get 'draw'
        get 'discard'
        get 'turn_end'
        get 'info'
        get 'recycle'
        get 'possible_moves'
        get 'perform'
        get 'select'
        get 'craft'
        get 'event_list', to: "games#event_list"
        get 'take'
      end
    end
  end
  # get '/find_opponent/:gid/:pid' => 'game#index'
  # get '/use_cards/:gid/:pid' => 'players#use_cards'
  # get '/draw/:gid/:pid' => 'players#draw'
  # get '/discard/:gid/:pid/:card_id' => 'players#discard'
  # get '/turn_end/:gid/:pid/' => 'players#turn_end'
  # get '/info/:gid/:pid/' => 'game#info'
  # get '/recycle/:gid/:pid/:card_id' => 'players#recycle'
  # get '/possible_moves/:gid/:pid' => 'players#possible_moves'
  # get '/perform/:gid/:pid/:rule_id' => 'players#perform'
  # get '/select/:gid/:pid/:target_id' => 'players#select_card_from_target'
end

app/views/home/game.html.slim
#maincontainer.row data-game_id=@game.id
  .primary
    .row#opponent data-opponent_id=opponent_id
      .col-md-2.side
        .row.life
        .row.shield
      .col-md-10.main
        .row.hand
        .row
          .col-md-7
            .row.action
          .col-md-5
            .row.used
    .row#common
      .col-md-2#field
      .col-md-1
        span.glyphicon.glyphicon-chevron-left aria-hidden="true"
      .col-md-4.moves
        .row
      .col-md-1
        span.glyphicon.glyphicon-chevron-right aria-hidden="true"
      .col-md-2.draw
        | draw
      .col-md-2.turn_end
        | End turn
    .row#player data-player_id=@player.id
      .col-md-2.side
        .row.life
        .row.shield
      .col-md-10.main
        .row
          .col-md-7
            .row.action
          .col-md-5
            .row.used
        .row.hand
  .secondary
    .row.discard
      .card.card-sm

app/views/home/lobby.html.slim
h2 Welcome to Game Lobby!
= link_to 'Open a Game', open_path, method: :post
table
  tr 
    th
    th Game No
    th team 1
    th team 2
  - @games.each do |game|
    tr
      td
        = link_to 'Return', game_path(game)
      td
        = game.id
      td
        = display_team(game.teams[0], game)
      td
        = display_team(game.teams[1], game)