config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'games#index'
  resources :users
  get '/auth/:provider/callback' => 'sessions#create'
  get '/auth/failure' => 'sessions#failure'
  get '/signout' => 'sessions#destroy', as: :signout
  get '/signin' => 'sessions#new', as: :signin
  # post '/open' => 'home#open', as: :open
  # patch '/join/:id/:team_id' => 'home#join', as: :join
  # get '/game/:id' => 'home#game', as: :game
  resources :games do
    resources :teams do
      patch 'join', on: :member
    end
    resources :players do
      member do
        get 'find_opponent'
        get 'use_cards'
        get 'draw'
        get 'discard'
        get 'turn_end'
        get 'info'
        get 'recycle'
        get 'possible_moves'
        get 'perform'
        get 'select'
        get 'craft'
        get 'event_list', to: "games#event_list"
        get 'take'
      end
    end
  end
  # get '/find_opponent/:gid/:pid' => 'game#index'
  # get '/use_cards/:gid/:pid' => 'players#use_cards'
  # get '/draw/:gid/:pid' => 'players#draw'
  # get '/discard/:gid/:pid/:card_id' => 'players#discard'
  # get '/turn_end/:gid/:pid/' => 'players#turn_end'
  # get '/info/:gid/:pid/' => 'game#info'
  # get '/recycle/:gid/:pid/:card_id' => 'players#recycle'
  # get '/possible_moves/:gid/:pid' => 'players#possible_moves'
  # get '/perform/:gid/:pid/:rule_id' => 'players#perform'
  # get '/select/:gid/:pid/:target_id' => 'players#select_card_from_target'
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :teams, dependent: :destroy
  has_many :players, -> { order(:sequence) }, through: :teams
  has_many :cards, as: :cardholder, dependent: :destroy
  has_many :turns, -> { order(:number) }, dependent: :destroy
  has_one :deck, dependent: :destroy

  enum :status, [ :prepare, :start, :over ]
  enum :field, { nothing: 0, metal: 1, tree: 2, water: 3, fire: 4, earth: 5 }

  def self.open( user, game_options: {}, team_options: {} )
    game = self.create!( game_options )
    team_amount ||= game.team_amount
    teams = game.teams
    team_amount.times do
      teams.create( team_options )
    end
    game.deck = Deck.new
    game.deck.shuffle true
    game.join_with( user, teams[0] )
  end

  def join_with( user, team )
    if team.position_available?
      team_index = teams.find_index team
      sequence = team_index + teams.count * team.players.count
      player = team.players.create sequence: sequence
      user.players << player
    end
    self
  end

  def ready?
    teams.all? do |team|
      !(team.position_available?)
    end
  end

  def begin( player )
    if prepare?
      deal_cards
      start!
      generate_turn
    end

    info( player )
  end

  def reinit
    deck.cards << players[0].cards << players[1].cards
    deck.shuffle
    #update( turn: 0 )
    prepare!
    turns.destroy_all
  end

  def info( player )
    game_status = as_json({
      except: [ :created_at, :updated_at ]
    })
    game_status[:myturn] = ( turn_player == player )
    game_status[:discard] = cards.where( position: -1 ).first
    game_status[:winning] = ( teams.index( player.team ) == winner )
    teams.each do |team|
      if team.players.include? player
        game_status[:current] = team.info(player)
      else
        game_status[:opponent] = team.info(player)
      end
    end
    game_status.merge( { possible_moves: [], choices: [] } )
  end

  def deal_cards
    players.each do |player|
      player.cards << deck.cards.first(player.hand_limit)
      # 不加這行測試會報錯
      deck.reload
    end
  end

  def opponent_team( player )
    teams.where.not(id: player.team)
  end

  def turn_player
    players[ ( first + turn ) % players.count ]
  end

  def last_player
    players[ ( first + turn - 1 ) % players.count ]
  end

  def turn_end
    increment!(:turn)
    generate_turn
  end

  def generate_turn
    turns.create!(number: turn, player: turn_player)
  end

  def current_turn
    turns[turn]
  end

  def last_turn
    turns[turn-1]
  end

  def draw_amount
    2
  end

  def exchange
    temp = teams[0].life
    teams[0].update( life: teams[1].life )
    teams[1].update( life: temp )
  end

  def trigger( player )
    3.times do
      trigger_rules = Rule.all_fitted( self, player, :passive )
      trigger_rules.each do |rule|
        rule.performed( player, [], self )
      end
    end
  end

  def trigger_continuous_effect
    players.each do |player|
      Rule.where( form: :power, subform: :continuous ).each do |rule|
        rule.performed(player, [], self)
      end
    end
  end

  def check_over
    winners = teams.select do |team|
      team.life > 0
    end
    if winners.count <= 1
      decide_winner( winners.first )
    end
    #save
  end

  def decide_winner( team )
    unless team.nil?
      update!( winner: teams.index( team ) )
      over!
    end
  end

  def eject(entity, rank)
    effected = []
    entity.each do |key, value|
      case key
      when "star"
        teams.each do |team|
          if team.has_star?(value) || (value == "all" && !team.has_star?("nothing"))
            team.star = :nothing
            effected.push( team )
          end
          team.save
        end
      when "field"
        effected = (teams.to_a) unless nothing?
        nothing!
      when "hero"
        players.each do |player|
          if rank >= 3 || !player.lengendary?
            player.deleted("hero")
          end
        end
      end
    end
    save
    effected
  end

  def discarded( card )
    ActiveRecord::Base.transaction do
      last_discard = cards.where( position: -1 ).first
      last_discard.update( position: card.position ) unless last_discard.nil?
      card.update( position: -1 )
      cards << card
    end
  end

  def event_list(viewer)
    turns.reverse.map do |turn|
      {
        number: turn.number,
        player: turn.player.id,
        events: turn.events.left_outer_joins(:rule).map { |event|
          rule_name = event.rule ? event.rule.chinese_name : nil
          if event.player != viewer && event.player.annex["hidden"] == "counter"
            {cards_used: event.cards_used.count, player: event.player.id}
          else
            {cards_used: event.cards_used.map{|c| c.to_hash}, rule: rule_name, effect: event.effect, player: event.player.id}
          end
        }
      }
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
    @player = current_player(@game)
    #render component: 'GameField', props: @game.info( @player )
  end

  def create
    if user_signed_in?
      @game = Game.open current_user
      redirect_to game_path(@game)
    else
      redirect_to signin_path
    end
  end

  def event_list
    @game = Game.find(params[:game_id])
    @player = Player.find(params[:id])
    if current_player?(@player, @game)
      render json: @game.event_list(@player)
    else
      head :forbidden
    end
  end
end

app/helpers/games_helper.rb
module GamesHelper
  def display_team( team, game )
    players = team.players.collect{ |p| p.user.name }
    players << link_to('Join', join_game_team_path(game, team), method: :patch) if team.position_available?
    raw players.join(',')
  end
end

app/views/games/index.html.slim
h2 Welcome to Game Lobby!
= link_to 'Open a Game', games_path, method: :post
table
  tr 
    th
    th Game No
    th team 1
    th team 2
  - @games.each do |game|
    tr
      td
        = link_to 'Return', game_path(game)
      td
        = game.id
      td
        = display_team(game.teams[0], game)
      td
        = display_team(game.teams[1], game)

app/views/games/show.html.slim
#maincontainer.row data-game_id=@game.id
  .primary
    .row#opponent
      .col-md-2.side
        .row
          .life
        .row
          .shield
        .row
          .hero
        .row
          .current_star
        .row
          .star_history
      .col-md-10.main
        .row.hand
        .row
          .col-md-7
            .row.action
          .col-md-5
            .row.used
    .row#common
      .col-md-2#field
      .col-md-1
        span.glyphicon.glyphicon-chevron-left aria-hidden="true"
      .col-md-4#moves
        .row
      .col-md-1
        span.glyphicon.glyphicon-chevron-right aria-hidden="true"
      .col-md-2
        button.confirm.btn.btn-default disabled="disabled"
          | Confirm
      .col-md-2#message_field
    .row#player data-id=@player.id
      .col-md-2.side
        .row
          .life
        .row
          .shield
        .row
          .hero
        .row
          .current_star
        .row
          .star_history
      .col-md-10.main
        .row
          .col-md-7
            .row.action
          .col-md-5
            .row.used
        .row.hand
  .secondary
    .row.discard
      .card.card-sm
    .row#event_list
  #choose.modal.fade.in data-backdrop="static" data-keyboard="false"
    .modal-lg.modal-dialog
      .modal-content
        .modal-header
          h4 選擇一張牌
        .modal-body
        .modal-footer
          button.btn.btn-primary
            | Confirm