config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'games#index'
  resources :users
  get '/auth/:provider/callback' => 'sessions#create'
  get '/auth/failure' => 'sessions#failure'
  get '/signout' => 'sessions#destroy', as: :signout
  get '/signin' => 'sessions#new', as: :signin
  # post '/open' => 'home#open', as: :open
  # patch '/join/:id/:team_id' => 'home#join', as: :join
  # get '/game/:id' => 'home#game', as: :game
  resources :games do
    resources :teams do
      patch 'join', on: :member
    end
    resources :players do
      member do
        get 'find_opponent'
        get 'use_cards'
        get 'draw'
        get 'discard'
        get 'turn_end'
        get 'info'
        get 'recycle'
        get 'possible_moves'
        get 'perform'
        get 'select'
        get 'craft'
        get 'event_list', to: "games#event_list"
        get 'take'
      end
    end
  end
  # get '/find_opponent/:gid/:pid' => 'game#index'
  # get '/use_cards/:gid/:pid' => 'players#use_cards'
  # get '/draw/:gid/:pid' => 'players#draw'
  # get '/discard/:gid/:pid/:card_id' => 'players#discard'
  # get '/turn_end/:gid/:pid/' => 'players#turn_end'
  # get '/info/:gid/:pid/' => 'game#info'
  # get '/recycle/:gid/:pid/:card_id' => 'players#recycle'
  # get '/possible_moves/:gid/:pid' => 'players#possible_moves'
  # get '/perform/:gid/:pid/:rule_id' => 'players#perform'
  # get '/select/:gid/:pid/:target_id' => 'players#select_card_from_target'
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | CFE
    = stylesheet_link_tag    "application", media: "all", "data-turbo-track" => "reload"
    = javascript_importmap_tags
    = javascript_include_tag "sprockets", "data-turbo-track" => "reload"
    = csrf_meta_tags
    = csp_meta_tag
    = vite_client_tag
    = vite_typescript_tag("application", "data-turbo-track" => "reload", :defer => true)
    meta name="viewport" content="width=device-width, initial-scale=1"
  body
    nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
      .container
        = link_to "CFE", root_url, class: 'navbar-brand'
        button.navbar-toggler type='button' data-bs-toggle='collapse' data-bs-target='#navbarSupportedContent' aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'
          span class='navbar-toggler-icon'
        .collapse.navbar-collapse id='navbarSupportedContent'
          .navbar-nav
            - if user_signed_in?
              .navbar-text.nav-item
                span> Logged in as
                = current_user.name
              = link_to 'Logout', signout_path, class: 'nav-link nav-item'
            - else
              = link_to 'Login', signin_path, class: 'nav-link nav-item', aria_current: 'page'
          - flash.each do |name, msg|
            - if msg.is_a?(String)
              li.alert class=( bootstrap_class_for(name) ) id=("flash_#{name}")
                = msg
    .container.mt-4.pt-2
      = yield
      = console if Rails.env.development?